Slovene localisation.
jaanos/helios-server pull request #1
Opened 2018-08-20 08:16 UTC by zanvd

2018-08-20 18:22 UTC, jaanos reviewed
Sem malo pregledal in popravil nekatere prevode. Preglej prosim, če se ti zdijo ustrezni popravki. Zaenkrat še nisem poskusil poganjati na strežniku.

2018-08-20 18:22 UTC, jaanos commented on locale/sl/LC_MESSAGES/django.po
> +"Language-Team: LANGUAGE <LL@li.org>\n"
Te podatke se lahko izpolni,

2018-08-20 18:22 UTC, jaanos commented on locale/sl/LC_MESSAGES/django.po
> +"            {#/if}"
Ali si preizkusil, če to dejansko deluje? Pričakoval bi namreč, da v prevodih ne moreš imeti kode iz predlog.

2018-08-20 18:22 UTC, jaanos commented on locale/sl/LC_MESSAGES/django.po
> +"Prišlo je do napake pri šifriranju vaše zahteve.\nProsimo kontaktiraje <EMAIL> in sporočite, da se je vaša enkripcija ustavila pri "
Mogoče bi rekli samo "Prosimo kontaktirajte nas", da ne bo maila med prevodi.

2018-08-20 18:41 UTC, zanvd commented on locale/sl/LC_MESSAGES/django.po
> +"Prišlo je do napake pri šifriranju vaše zahteve.\nProsimo kontaktiraje <EMAIL> in sporočite, da se je vaša enkripcija ustavila pri "
Lahko, ja.

2018-08-20 18:43 UTC, zanvd commented on locale/sl/LC_MESSAGES/django.po
> +"Prišlo je do napake pri šifriranju vaše zahteve.\nProsimo kontaktiraje <EMAIL> in sporočite, da se je vaša enkripcija ustavila pri "
Lahko, ja.

2018-08-20 18:44 UTC, zanvd commented on locale/sl/LC_MESSAGES/django.po
> +"            {#/if}"
Žal mi lokalno ne deluje, tako da nisem mogel pognati.
Tudi sam nisem prepričan, kako je s tem.

2018-08-20 18:44 UTC, zanvd commented
Popravki se mi zdijo v redu.

2018-08-20 20:33 UTC, jaanos commented on locale/sl/LC_MESSAGES/django.po
> +"            {#/if}"
Po dokumentaciji sodeč to ne bo delovalo:

https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#blocktrans-template-tag

2018-08-21 05:57 UTC, zanvd commented on locale/sl/LC_MESSAGES/django.po
> +"            {#/if}"
Hvala, bom popravil.
Sem opazil, da moram tudi popraviti spremenljivke, ki so vključene v prevod.

2018-08-21 06:57 UTC, jaanos commented on locale/sl/LC_MESSAGES/django.po
> +"            {#/if}"
Ja, sem pushal v tvoj repozitorij, tako da bi s pullom moral dobiti moj commit.

2018-08-21 20:58 UTC, zanvd commented on locale/sl/LC_MESSAGES/django.po
> +"            {#/if}"
Sem dobil. Hvala.
Ali mogoče veste, kaj pomeni spremenljivka $T v html predlogah? Sam ne najdem pomena $ znaka za djangov template engine in bom težko ustrezno popravil lokalizacijo.

2018-08-21 21:35 UTC, jaanos commented on locale/sl/LC_MESSAGES/django.po
> +"            {#/if}"
Kolikor vidim, to sploh ni Djangov template, pač pa se servira statično (in se parsa z Javo), kot vse strani v podmapah, navedenih pri `document_root`:

https://github.com/jaanos/helios-server/blob/30dfe364344e91d983a32cbc5aebd06c0605d3bf/urls.py#L12-L17

Tam tudi `i18n` ne bo deloval, tako da bo treba najti drugo rešitev. Predlagam, da datoteke v teh mapah in njihove prevode zaenkrat pustiš, kot so, pa bomo kasneje poskusili drugače rešiti.

2018-08-21 21:43 UTC, zanvd commented on locale/sl/LC_MESSAGES/django.po
> +"            {#/if}"
Torej se lahko ta PR zapre, ker so vse datoteke vključene v ```document_root``` in nikjer ne bo deloval ```i18n```?

2018-08-21 22:54 UTC, jaanos commented on locale/sl/LC_MESSAGES/django.po
> +"            {#/if}"
Ne ne, samo datoteke iz `heliosbooth` in `heliosverifier` ne bodo delovale. Na datotekah iz `helios_auth` in `server_ui` bo `i18n` deloval.

2018-08-22 06:20 UTC, zanvd commented on locale/sl/LC_MESSAGES/django.po
> +"            {#/if}"
Ok. Včeraj sem popravil določene stvari, a sem s pushom hotel počakati do vašega odgovora, tako da bom to storil danes.

2018-08-22 16:17 UTC, zanvd commented
Prosim za ponovni pregled.

2018-08-28 15:39 UTC, jaanos requested changes
Sem dal še par komentarjev, kjer je treba popraviti.

Bom poskusil poiskati še rešitev za `heliosbooth` in `heliosverifier`.

2018-08-28 15:39 UTC, jaanos commented on helios_auth/templates/index.html
> +    {% blocktrans %}You are currently logged in as<br /><b>{{user.user_id}}</b> via <b>{{user.user_type}}</b>.{% endblocktrans %}
Po [dokumentaciji](https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#blocktrans-template-tag) sodeč to ne bo delovalo - treba bo naredit nekako tako:
```django
{% blocktrans with user_id=user.user_id user_type=user.user_type %}
You are currently logged in as<br /><b>{{user_id}}</b> via <b>{{user_type}}</b>.
{% endblocktrans %}
```

2018-08-28 15:39 UTC, jaanos commented on server_ui/templates/confirm.html
> +    {% trans 'Forgot your password?' %} <a href="{% url "helios_auth.auth_systems.password.password_forgotten_view" %}?return_url={% url "server_ui.views.cast_confirm" %}">{% blocktrans %}Have it ema
Tukaj bi bilo bolje, če se razdeli na dva dela, da nimamo HTML značk v prevodih (sploh ne takih brez para).

2018-08-28 15:39 UTC, jaanos commented on server_ui/templates/done.html
> +    {% blocktrans %}A vote was successfully cast for <b>{{voter.voter_id}}</b>, with vote fingerprint:{% endblocktrans %}
Tukaj bo spet treba uvesti spremenljivko pri `blocktrans`.

2018-08-28 15:39 UTC, jaanos commented on server_ui/templates/done.html
> +    {% trans 'Visit the' %}<a href="{% url "helios.views.one_election_view" election.uuid %}">{% blocktrans %}election homepage</a>.{% endblocktrans %}
Značka HTML naj gre ven iz prevoda.

2018-08-28 15:39 UTC, jaanos commented on server_ui/templates/election_tallied.html
> +  <h2 class="title">{% blocktrans %}Election {{election.name}} Already Tallied{% endblocktrans %}</h2>
Spet spremenljivka.

2018-08-28 16:46 UTC, zanvd commented
Hvala. Bom popravil.

2018-08-28 20:42 UTC, jaanos commented
Mimogrede, opažam še, da niso prevedene datoteke v `helios/templates/` ter `templates/500.html`.

2018-08-29 22:39 UTC, jaanos commented
Sem ugotovil, kako prevajati še v datotekah, ki se servirajo statično. Django namreč ponuja še [prevode za JavaScript](https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#internationalization-in-javascript-code), ki se seveda lahko uporabijo tudi v dokumentih HTML. Trik je, da se torej vključi JavaScript s prevodi in funkcijami zanje:

https://github.com/jaanos/helios-server/blob/89e1964303f58eaa6ad92dd992522a2547bf4aa9/heliosbooth/vote.html#L28-L32

Prevode se potem v JavaScriptu dobi s funkcijo `gettext` (ali katero sorodno). Ko pa želimo prevajati besedilo v HTML, zgornja koda omogoča, da se vstavi značka `<script>`, kjer se na trenutno mesto zapiše prevod:
```HTML
<script>d.w(gettext('besedilo'))</script>
```
Če se besedilo za prevajanje nahaja v atributu značke HTML, potem je treba na tak način vstaviti celo značko (seveda se lahko `gettext` uporabi samo na delu, ki se dejansko prevaja), ali pa se atribut značke nastavi z jQuery.

S takim pristopom sem že prevedel `heliosbooth/vote.html` in `heliosverifier/verify.html`, treba pa je še prevesti `heliosbooth/single-ballot-verify.html`. Za datoteke v `heliosbooth/templates/` pa `d.w` ne bo deloval (ta vsebina se naloži naknadno, zato bi tak klic povozil vsebino dokumenta), zato sem ustrezne značke opremil z atributom `id` (kjer ni bilo značke, sem naredil `<span>`) in odstranil besedilo, potem pa sem na koncu dodal skripto, ki z jQueryjem nastavi ustrezen prevod, npr.

https://github.com/jaanos/helios-server/blob/89e1964303f58eaa6ad92dd992522a2547bf4aa9/heliosbooth/templates/election.html#L4-L5
https://github.com/jaanos/helios-server/blob/89e1964303f58eaa6ad92dd992522a2547bf4aa9/heliosbooth/templates/election.html#L28-L30

Poleg za `election.html` sem to naredil še za `question.html` (kjer je stvar nekoliko bolj zapletena), tako da bi te prosil, da narediš še za ostale datoteke v `heliosbooth/templates/`. Pri njih ni potrebno vključevati kataloga, saj se ta podeduje iz `vote.html`. Kar se tiče ID-jev značk, bi te prosil, da se vsak ID začne z imenom datoteke, kjer se nahaja, preostanek pa je potem ločen s podčrtajem (tako se npr. vsi ID-ji v `question.html` začnejo s `question_`). Pazi še, da v teh datotekah ne dodajaš zavitih oklepajev (npr. v JavaScript), saj se ti interpretirajo kot del predloge.

Da generiraš datoteko s prevodi, poženi
```bash
django-admin makemessages -d djangojs -l sl -e html
```
Ta ukaz bo dopolnil datoteko `locale/sl/LC_MESSAGES/djangojs.po`, kamor potem vneseš prevode. Privzeto sicer išče po datotekah s končnico `js` - parameter `-e html` to spremeni, a še vedno pričakuje JavaScript. Zato se bo seveda izpisal cel kup opozoril, ki jih lahko ignoriraš; bolj pomembno pa je, da preveriš, ali so bili zajeti vsi prevodi. V JavaScriptu se namreč regularne izraze piše med `//` - ker pa imajo poševnice drugačen pomen v HTML, lahko zgornji ukaz za kak `gettext` misli, da je znotraj takega izraza in ga zato ne vidi. Če se to zgodi, nekam pred tem postavi HTML-jev komentar `<!--/-->`, da bo prevod padel iz regularnega izraza.

Ko končaš s prevajanjem, lahko pretvoriš prevode v obliko `.mo`:
```bash
django-admin compilemessages
```
Ta ukaz bo tudi opozoril, če je kaj narobe. Datoteke `.mo` so izpeljane binarne datoteke, zato sem v `.gitignore` dodal pravilo, naj se ne dodajo v commite.

2018-09-13 20:28 UTC, zanvd commented
Prosim za preverbo manjkajočih prevodov in popravke spremenljivk.
Sedaj se bom lotil še JS prevodov.

2018-09-14 18:02 UTC, jaanos reviewed
Sem dal par komentarjev pri vnosu značk za prevajanje v predlogah. Bom pogledal še same prevode in morebitne popravke vključil kar v commit.

2018-09-14 18:02 UTC, jaanos commented on helios/templates/election_cast_confirm.html
> +  var message = "You have not yet cast your ballot! Make sure to complete the voting process if you want your vote to count.";// TODO
Čeprav je to JavaScript, se nahaja v Djangovi predlogi, tako da lahko uporabiš `{% trans %}` (seveda znotraj JavaScriptovih navednic).

2018-09-14 18:02 UTC, jaanos commented on helios/templates/election_register.html
> +    {% blocktrans with user=user %}You are currently logged in as {{user.user_id}} [{{user.user_type}}]{% endblocktrans %}
Mislim, da to ne bo delovalo - bo potrebno uvesti npr. `user_id=user.user_id` in `user_type=user.user_type`.

2018-09-14 18:02 UTC, jaanos commented on helios/templates/election_view.html
> +{% blocktrans with election_type=election.election_type %}this {{election.election_type}} is <u>not</u> featured on the front page.{% endblocktrans %}
Tukaj si uvedel `election_type`, tako da ga kot takega tudi uporabi v prevodu.

Bi sicer moral pogledati, kaj točno to je - morda bo treba prevesti tudi to vrednost.

2018-09-14 18:02 UTC, jaanos commented on helios/templates/election_view.html
> +but has been extended until {{ election.voting_extended_until }} (UTC).{% endblocktrans %}
Podobno kot zgoraj bo potrebno uvesti vse tri spremenljivke.

2018-09-14 18:02 UTC, jaanos commented on helios/templates/election_view.html
> +{% blocktrans with election=election %}This {{election.election_type}} ends at the administrator's discretion.{% endblocktrans %}
Spet isto, v obeh primerih.

2018-09-14 18:02 UTC, jaanos commented on helios/templates/stats_elections.html
> +<b><a href="{% url "helios.views.one_election_view" election.uuid %}">{{election.name}}</a></b> {% trans 'by' %} <a href="mailto:{{election.admin.info.email}}">{{election.admin.pretty_name}}</a> -- {
Tukaj bi prišlo v upoštev več oblik glede na število. Sodeč po [dokumentaciji](https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#blocktrans-template-tag) bi šlo tako:
```django
{% blocktrans count num_voters=election.num_voters %}
{{num_voters}} voter
{% plural %}
{{num_voters}} voters
{% endblocktrans %}
```
Podobno narediš še za `num_cast_votes`. V datoteki s slovenskimi prevodi se bodo potem pojavila štiri polja za prevod tega vnosa (za 1, 2, 3/4 in ostale vrednosti).

2018-09-14 18:02 UTC, jaanos commented on helios/templates/stats_problem_elections.html
> +<b><a href="{% url "helios.views.one_election_view" election.uuid %}">{{election.name}}</a></b> -- {{election.num_voters}} {% trans 'voters' %}
Podobno kot zgoraj naj se upošteva število.

2018-09-14 18:02 UTC, jaanos commented on helios/templates/stats_recent_votes.html
> +<b><a href="{% url "helios.views.one_election_view" election.uuid %}">{{election.name}}</a></b> -- {{election.last_cast_vote}} {{election.num_recent_cast_votes}} {% trans 'recently cast votes' %}
Spet upoštevaj število.

2018-09-14 18:04 UTC, jaanos commented
Še to bo treba preveriti - kaj natanko je `election.election_type` (glej https://github.com/jaanos/helios-server/pull/1#discussion_r217789421).

2018-09-14 18:07 UTC, jaanos commented on helios/templates/election_view.html
> +{% blocktrans with election=election %}This {{election.election_type}} ends at the administrator's discretion.{% endblocktrans %}
Tukaj v pregledu ne pokaže - gre za vrstico bolj gor:
https://github.com/jaanos/helios-server/blob/ca9727dea2c1fc0cba50b431e6443576fc437ba8/helios/templates/election_view.html#L188

2018-09-14 19:25 UTC, jaanos commented
Sem naredil še nekaj sprememb v prevodih. Predlagal bi, da v besedilu uporabnika vikaš (kakor večinoma že počneš), medtem ko naj bo na gumbih in povezavah velelnik v ednini (tj., tukaj uporabnik daje sistemu ukaze). Če opaziš, da je kje še drugače (mogoče sem tudi sam vnesel kako nedoslednost), lahko popraviš - sicer pa bom dal na strežnik, ko bo prevajanje končano, pa se bo takrat vse skupaj preklikalo in preverilo.

2018-09-15 09:37 UTC, zanvd commented on helios/templates/election_register.html
> +    {% blocktrans with user=user %}You are currently logged in as {{user.user_id}} [{{user.user_type}}]{% endblocktrans %}
Za spremenljivke znotraj blocktrans nisem prepričan, če je potrebno nastaviti končno vrednost, ali je lahko to tudi objekt - v dokumentaciji nisem zasledil specifičnih navodil glede tega.
Bom pretvoril v končne vrednosti, čeprav bi se mi zdelo logično, da je to zgolj način pošiljanja argumentov v funkcijo in bi bila možna uporaba objekta.

2018-09-16 16:17 UTC, jaanos commented on helios/templates/election_register.html
> +    {% blocktrans with user=user %}You are currently logged in as {{user.user_id}} [{{user.user_type}}]{% endblocktrans %}
Piše v dokumentaciji za `blocktrans`, da dostopanje do atributov objektov ne deluje. Mislim, da gre tukaj za omejitev knjižnice za prevajanje.

2018-09-17 20:15 UTC, zanvd commented on helios/templates/election_register.html
> +    {% blocktrans with user=user %}You are currently logged in as {{user.user_id}} [{{user.user_type}}]{% endblocktrans %}
Našel sem zgolj spodnji sestavek, iz česar pa nisem povsem prepričan, če so res potrebne posamezne spremenljivke. Vseeno sem jih dodal, tako da sedaj ni objektov.
> To translate a template expression – say, accessing object attributes or using template filters – you need to bind the expression to a local variable for use within the translation block.

2018-09-18 21:01 UTC, zanvd commented
Preveril sem še za _election_type_. V _helios/models.py_ sta definirana dva tipa:
```
ELECTION_TYPES = (
    ('election', 'Election'),
    ('referendum', 'Referendum')
    )
```
Mogoče veste, kako bi lahko prevedel tekst iz modela? Kar sem sam iskal, ni bilo nič trivialnega.

2018-09-18 23:05 UTC, merged

2018-09-18 23:28 UTC, jaanos commented
Vidim, da sem uspel že kar mergeat:) Sem to rešil z `ugettext` in `pgettext`, da se stvari potem lepo sklanjajo v odvisnosti od tipa volitev.

Zdaj je stvar na https://lkrv.fri.uni-lj.si/helios/sl/, tako da te prosim, da preklikaš in pregledaš, če je vse prevedeno in na mestu, pa če res vse deluje. Če boš še kaj popravljal, nadaljuj iz veje `slovene` na mojem repozitoriju in potem odpri pull request vanjo.

2018-09-22 08:56 UTC, zanvd commented
Živjo,
ko želim ustvariti volitve, dobim takoj obrazec z angleškimi oznakami in tekstom za pomoč. Če se ne motim, so te stvari definirane v _view.py_ vrstica 223. Lahko prosim preverite in mi svetujete, kako rešiti to zadevo?
Tudi sicer je v omenjeni datoteki še kar nekaj teksta, katerega bi bilo najverjetneje potrebno prevesti.
Pregledal sem še, zakaj je sam GUI drugačen od Heliosove strani. V _base.html_ preverja nastavitev _MASTER_HELIOS_, katero bi bilo potrebno nastaviti, da bi bil, predvidevam, produkcijski prikaz. Sama nastavitev je v _settings.py_:
`32: # is this the master Helios web site?
33: MASTER_HELIOS = (get_from_env('MASTER_HELIOS', '0') == '1')`

Lp,
Žan

2018-09-22 11:32 UTC, jaanos commented
Besedilo za obrazec se nahaja v `helios/forms.py`:
https://github.com/jaanos/helios-server/blob/2962e0780d25621171ecf68cad180ac92b4dd358/helios/forms.py#L13-L17
Imena polj se lahko določijo s parametrom `label`, očitno pa Django sam ugane ime iz imena spremenljivke, kjer `label` ni podan. Za prevajanje bo torej potrebno povsod določiti `label`.

Treba bo torej še skozi vse datoteke `.py` in še tam poskrbeti za prevode. Treba bo torej uvoziti ustrezne funkcije, npr.
https://github.com/jaanos/helios-server/blob/2962e0780d25621171ecf68cad180ac92b4dd358/helios/models.py#L13
Potem lahko za enostavno prevajanje uporabiš `ugettext`, za primere z množino pa `ungettext` (`pgettext` se uporabi, če je potreben kontekst - tj., če se lahko isti niz prevede na več načinov). Več detajlov je v [dokumentaciji](https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#internationalization-in-python-code) (posebej glej glede vstavljanja podatkov v prevode).

`MASTER_HELIOS` sem pa zdaj na strežniku nastavil na `True`, tako da zdaj prva stran vključuje uvodno besedilo.

2018-09-22 11:42 UTC, zanvd commented
Najlepša hvala za izčrpen odgovor. Se bom lotil dela.

Hvala.